apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed-job
spec:
  template:
    spec:
      containers:
      - name: db-seed
        image: 'nyuappsec/assign3-db:v0'
        command: ["/bin/sh"]
        args: ["-c","mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --database=${MYSQL_DATABASE} --host=mysql-service -f < /docker-entrypoint-initdb.d/db-seed.sql"]
        env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: newsecret
                key: password
          - name:  MYSQL_DATABASE
            value: GiftcardSiteDB
      restartPolicy: Never
  backoffLimit: 3