apiVersion: batch/v1
kind: Job
metadata:
  name: dbmigration
spec:
  template:
    spec:
      containers: 
      - name: dbmigration
        image: nyuappsec/assign3:v0
        command: ['python3', 'manage.py', 'migrate']
        #command: ["shellscript.sh"]
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: newsecret
                  key: password

            - name: MYSQL_DB
              value: GiftcardSiteDB

            - name: MYSQL_HOST
              value: mysql-service

            - name: ALLOWED_HOSTS
              value: "*,"

            - name: ADMIN_UNAME
              valueFrom:
                secretKeyRef:
                    name: newsecret
                    key: username

            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                    name: newsecret
                    key: password

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                    name: newsecret
                    key: secret_key

      restartPolicy: Never
  backoffLimit: 4